name: message_passing
author: trupti
version: 0.1.0
description: A demonstration of a simple service
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: trupti/message_passing:0.1.0
number_of_agents: 4
deployment: {}
---
public_id: trupti/message_passing_abci:0.1.0
type: skill
models:
  params:
    args:
      service_registry_address: null
      share_tm_config_on_startup: false
      on_chain_service_id: null
      setup:
        all_participants: ${ALL_PARTICIPANTS:list:["0x0000000000000000000000000000000000000000"]}
        safe_contract_address: '0x0000000000000000000000000000000000000000'
        consensus_threshold: null
      hello_world_message: ${HELLO_WORLD_STRING_0:str:HELLO_WORLD!}
  benchmark_tool:
    args:
      log_dir: /benchmarks
---
public_id: trupti/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_HELLO_WORLD_RPC:str:"http://host.docker.internal:8545"}
      chain_id: 31337
      poa_chain: false
      default_gas_price_strategy: eip1559